### ISSUE TITLE
Naquadah Reactors Need a Large Buff

### ISSUE THREAD

**Issue by Vyraal1** [EmosewaPixel/GregicAdditions#16]
So was looking over some Enriched Naquadah math and found that it's in need of a pretty large buff.

According to JEI, Enriched Naquadah outputs **3,000,320 EU per 200mb** which gives it an output of **~15k EU/mb.**

According to JEI, it has a creation cost of:
* 1,058,400 EU in the EBF
* 33,720 EU in the Vacuum Freezer
* 40,960 EU in the Fluid Extractor

for a total of **1,133,080 EU per 144 mb** or **7.8k EU/mb**. However this is assuming this is done at MV costs, and not overclocking, which is a bad assumption because by the time the player reaches a stage to use Naquadah (EV/IV), they will probably have overclocked electric blast furnaces. Just overclocking it to HV would double the total EU cost to around **16.6k/mb** which already makes Enriched Naquadah and Naquadah Reactors (when the update to fix single block generators is released to Curseforge) **_energy negative._**

In comparsion, GT5U had Naquadah Reactors Mk.I consuming Naquadah bolts, which are 8 bolts per ingot. Each bolt ended up producing 20,000,000 of EU at 80% efficiency, so **16M EU per bolt**, or converted to liquid fuel rates that's 16M EU for every 18mb, leading to a total output of **_~888k/mb for Naquadah._** Even though I'm not asking to replicate the behavior from GT5U exactly, that's a vast difference in power from what is currently implemented in GA at a net loss of -1.6k EU/mb.

**Comment by EmosewaPixel** [comment]
In GT5U, Naquadah spawned is asteroids that spawned every few million blocks. In GTCE Enriched Naquadah spawn in one in every 10-ish chunks. That's why it's so nerfed.

**Comment by Vyraal1** [comment]
I think using numbers to say that it generates once every  few million blocks is a bit misleading, the % chances were actually per chunk, not blocks, since there were few blocks in the end. Also asteroids were pretty easy/common to find since they were floating in the air and very visible to players, I recall Sheldonite being more difficult to obtain. And the majority of the Enriched Naquadah you received anyways was from byproducts of normal Naquadah.

Lastly, even coal is energy positive. The difficulties in Naqaudah wasn't really obtaining it (although I agree it it was more difficult than something like copper), it was in the processing and automating it. I think a small buff isn't enough, it would need to be a substantial one.
