### ISSUE TITLE
Combustible Gases not functioning in Gas Turbine

### ISSUE THREAD

**Issue by pyure** [EmosewaPixel/GregicAdditions#17]
Methane and Hydrogen seem to have been moved to the Steam turbine.  I think its an accident since they'd literally just sit in the turbine and accomplish nothing.

If this was a weirdly deliberate thing, can you please make it configurable?  (And if you do so, you should rename or at least re-tooltip the Gas Turbine, which currently still claims it combusts flammable gases)

**Comment by TedKnudsen** [comment]
Thx Pixel
