### ISSUE TITLE
MAX Voltage Transfomer has inaccurate UV output

### ISSUE THREAD

**Issue by Vyraal1** [EmosewaPixel/GregicAdditions#18]
![image](https://user-images.githubusercontent.com/26587049/46970552-706aa600-d087-11e8-873d-923462c07380.png)

I was considering making a setup that could use superconductor wire to transfer power around the base, however I would need to transform it down sometimes, this transforms to a voltage that's still way beyond UV.

**Comment by EmosewaPixel** [comment]
I don't see the issue here.
