### ISSUE TITLE
Some craft issue

### ISSUE THREAD

**Issue by Wettix** [EmosewaPixel/GregicAdditions#19]
GregicAdditions-1.12.2-1.2.0
jungle planks cannot be crafted without saw with the *2 recipe
![ss 2018-10-16 at 01 10 49](https://user-images.githubusercontent.com/43379174/46983344-5c06c780-d0e0-11e8-9fdc-434148fa43ee.jpg)

but if i set to false that
        # Set to false to disable generated wood sawing recipes
        B:"A saw is required to get 4 Planks per Log"=false
the recipe work with * 4

if i set to false disable 3x3 recipes
        # Set these to false to disable the generated Compressor recipes for blocks
        B:"Compression - Generate Compressor recipes for blocks"=true
        B:"Compression - Remove 3x3 crafting recipes for blocks"=false

jei show me 2 same recipe for block and ingot 3x3 crafting
![ss 2018-10-16 at 01 24 22](https://user-images.githubusercontent.com/43379174/46983768-485c6080-d0e2-11e8-855d-803c13b6c0b0.png)
![ss 2018-10-16 at 01 24 30](https://user-images.githubusercontent.com/43379174/46983769-4a262400-d0e2-11e8-8968-6478f5313407.jpg)

**Comment by EmosewaPixel** [comment]
Yeah, I have no idea what's wrong with Jungle. The second one has nothing to do with GA. You have duplicating recipes in your pack
