### ISSUE TITLE
Alternative item names for Tanks

### ISSUE THREAD

**Issue by pyure** [EmosewaPixel/GregicAdditions#20]
Pixel, is there any way for you guys to register items (such as Drums) so that I can reference them in crafttweaker and get an IItemStack?  

![image](https://user-images.githubusercontent.com/8617528/46986945-fc002900-d0bf-11e8-8507-5b8bf37167a5.png)

GTCE devs frown upon using <gregtech:machine:xxxx> and I'm trying to avoid such.

**Comment by Vyraal1** [comment]
Agreed, it would be nice to just type something like <gregtech:bronze:drum> instead of getting the item ID itself.

**Comment by EmosewaPixel** [comment]
I'm closing this since Arch said he was going to add it to GTCE.
