### ISSUE TITLE
Naquadah Reactor Mk. 5 doesn't seem to work

### ISSUE THREAD

**Issue by Vyraal1** [EmosewaPixel/GregicAdditions#21]
![image](https://user-images.githubusercontent.com/26587049/46987387-ff94af80-d0c1-11e8-86ac-42ad1de2fca8.png)

In comparison, Mk. 4
![image](https://user-images.githubusercontent.com/26587049/46987393-0ae7db00-d0c2-11e8-96ee-65b16fe2ae91.png)

My best guess is that is requires 16,384 mb of Enriched Naquadah to start the recipe.

Gregtech Community Edition: 117
GA: 1.2.0 (Curseforge)
GBUL 1.0.3 (Curseforge)

**Comment by EmosewaPixel** [comment]
In that case, all I can do is remove it.
