### ISSUE TITLE
LOLOLOLOLOL #46

### ISSUE THREAD

**Issue by Vyraal1** [EmosewaPixel/GregicAdditions#23]
![image](https://user-images.githubusercontent.com/26587049/47261156-83221800-d497-11e8-8e12-be0f05e2f861.png)

![image](https://user-images.githubusercontent.com/26587049/47261160-8ae1bc80-d497-11e8-9ead-fe80b17eeafd.png)

**Comment by Kaperios** [comment]
Git gud issue

**Comment by ThatGravyboat** [comment]
![image](https://user-images.githubusercontent.com/26934102/47261217-ef574880-d4a4-11e8-9db5-9b152d901149.png)

**Comment by Kaperios** [comment]
![image](https://user-images.githubusercontent.com/17909958/47261285-f5145480-d4cb-11e8-8b1f-e7cba7351594.png)
