### ISSUE TITLE
Fusion Reactor Mark III Doesn't Have An OreDict Circuit

### ISSUE THREAD

**Issue by Vyraal1** [EmosewaPixel/GregicAdditions#25]
![image](https://user-images.githubusercontent.com/26587049/47301144-3a2fa800-d5ec-11e8-9083-c406fc54b4af.png)

For comparison, something like the Fusion Reactor Mark II has  the same circuit requirements,but they are oredictionaried.
![image](https://user-images.githubusercontent.com/26587049/47301181-529fc280-d5ec-11e8-81e3-e26744b35a7c.png)

**Comment by EmosewaPixel** [comment]
Well, that's how it was in GT5U, though I think it'd make more sense for them to be Wetware Mainframes instead.
