### ISSUE TITLE
Assembly Line Outputs (Needs Circuits)

### ISSUE THREAD

**Issue by Vyraal1** [EmosewaPixel/GregicAdditions#26]
![image](https://user-images.githubusercontent.com/26587049/47376239-1dfd3b00-d6c0-11e8-8c3a-1624c947b9ba.png)

![image](https://user-images.githubusercontent.com/26587049/47376264-26557600-d6c0-11e8-8aef-21d5f0547379.png)

Normally this wouldn't be a problem due to the styrene butadiene rubber versus soldering alloy, however most players will probably build a large assembly line to handle multiple inputs and fluids. Would it be possible to add a programming circuit to differentiate?

**Comment by EmosewaPixel** [comment]
🤔 I'm unsure whether to go through with this.

**Comment by Vyraal1** [comment]
Yeah with some more thinking this one is a bit trickier, it just might be better to give the motor another item that an electric piston doesn't have rather than a circuit. Either way, it will end up with a player usually making motors when they intended to make pistons.

**Comment by EmosewaPixel** [comment]
I went with the circuit idea.
