### ISSUE TITLE
Crashing when adding gregic Additons to pack

### ISSUE THREAD

**Issue by Saereth** [EmosewaPixel/GregicAdditions#33]
mc 1.12.2
gregtech community edition 1.0.124
gregic additions 1.2.3

When I added this it crashes with the message 
net.minecraftforge.fml.common.LoaderException: Found at least one invalid recipe. Please read the log above for more details.

 (full crash log here:)
https://hastebin.com/ajodiqahur.rb

the latest.log shows:
[11:30:57] [main/FATAL] [gregtech]: Seems like invalid recipe was found. Loading will not continue.
[11:30:57] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  Wizardry Plugin (wizardry-0.9.7.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.15.jar)
  AstralCore (astralsorcery-1.12.2-1.10.1.jar)
  JEIDLoadingPlugin (JustEnoughIDs-1.0.2-26.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.43.jar)
  BNBGamingCore (BNBGamingCore-1.12.2-0.10.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  llibrary (llibrary-core-1.0.5-1.12.2.jar)
  ForgelinPlugin (Forgelin-1.8.0.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.4.jar)
  LoadingPlugin (Quark-r1.5-130.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.2-1.12.2.jar)
  LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
  Botania Tweaks Core (botaniatweaks-1.7.1.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.2.2.1.jar)
  DLFMLCorePlugin (DynamicLights-1.12.2.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.4.1-112-universal.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.20.jar)
  GottaGoFastLoader (gottagofast-1.1.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 11/8/18 11:30 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: Found at least one invalid recipe. Please read the log above for more details.

actual file: https://gist.github.com/Saereth/5b9f1b43739e8170f34089d1c4dc356e

there seems to be a lot of wrench recipes being duplicated around 5736+ not sure if its related here. 

Pack boots without issue if I remove gregic additions

**Comment by EmosewaPixel** [comment]
Ok, the Wrench recipes seem to be causing the crash. Did you change something in the config?

**Comment by Saereth** [comment]
no nothing in the config, and I dont think this is your issue, booting it up just with GT and gregic additions its working fine. I think its probably using one of our content tweakered materials that are conflicting with it. Just on a whim we commented out our scripts for custom materials and it stopped crashing as well so I believe there's some duplication going on with our script. Gonna close for now as I assume its on our end, may re-open if we get more info and it turns out not to be. Thanks!
