### ISSUE TITLE
Machines can't share output(Only tested with coke oven chute and faucet) 

### ISSUE THREAD

**Issue by NikolaiM88** [EmosewaPixel/GregicAdditions#36]
The coke oven faucet and chute, can't be shared between 2 multiblock structures, like you used to be able to with oldschool gregtech multiblocks. Only one of the connected machines will work, and all other machines connected to the outputs of the currently "working" coke oven stops working.

**Comment by EmosewaPixel** [comment]
Intended. GT multiblocks can't share hatches.
