### ISSUE TITLE
not work with mek

### ISSUE THREAD

**Issue by xly2000** [EmosewaPixel/GregicAdditions#4]
can u fix it?

**Comment by xly2000** [comment]
---- Minecraft Crash Report ----
// I blame TheEmosewaPixel, author of Gregic Additions.

Time: 2018-09-29 12:32:04 CST
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Gregic Additions (gtadditions)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
    at gregicadditions.recipes.GARecipeAddition.postInit(GARecipeAddition.java:310)
    at gregicadditions.GregicAdditions.postInit(GregicAdditions.java:58)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
    at net.minecraft.client.Minecraft.init(Minecraft.java:534)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3929)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 2011538216 bytes (1918 MB) / 3293577216 bytes (3141 MB) up to 7397179392 bytes (7054 MB)
  JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx7936m -Xms256m -XX:PermSize=256m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.4.2760 94 mods loaded, 94 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                      | Version                  | Source                                          | Signature                                |
       |:------ |:----------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
       | UCHIJ  | minecraft               | 1.12.2                   | minecraft.jar                                   | None                                     |
       | UCHIJ  | mcp                     | 9.42                     | minecraft.jar                                   | None                                     |
       | UCHIJ  | FML                     | 8.0.99.99                | forge-1.12.2-14.23.4.2760.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHIJ  | forge                   | 14.23.4.2760             | forge-1.12.2-14.23.4.2760.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHIJ  | foamfixcore             | 7.7.4                    | minecraft.jar                                   | None                                     |
       | UCHIJ  | applecore               | 3.1.4                    | AppleCore-mc1.12.2-3.1.4.jar                    | None                                     |
       | UCHIJ  | crafttweaker            | 4.1.9                    | CraftTweaker2-1.12-4.1.9.jar                    | None                                     |
       | UCHIJ  | mtlib                   | 3.0.5                    | MTLib-3.0.5.jar                                 | None                                     |
       | UCHIJ  | modtweaker              | 4.0.13                   | modtweaker-4.0.14.jar                           | None                                     |
       | UCHIJ  | jei                     | 4.12.1.217               | jei_1.12.2-4.12.1.217.jar                       | None                                     |
       | UCHIJ  | appleskin               | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                      | None                                     |
       | UCHIJ  | aquaculture             | 1.6.6                    | Aquaculture-1.12.2-1.6.6.jar                    | None                                     |
       | UCHIJ  | betteradvancements      | 0.0.5.17                 | BetterAdvancements-1.12.2-0.0.5.17.jar          | None                                     |
       | UCHIJ  | betterquesting          | 3.5.267                  | BetterQuesting-3.5.267.jar                      | None                                     |
       | UCHIJ  | forestry                | 5.8.1.322                | forestry_1.12.2-5.8.1.322.jar                   | None                                     |
       | UCHIJ  | binniecore              | 2.5.0.168                | binnie-mods-1.12.2-2.5.0.168.jar                | None                                     |
       | UCHIJ  | binniedesign            | 2.5.0.168                | binnie-mods-1.12.2-2.5.0.168.jar                | None                                     |
       | UCHIJ  | genetics                | 2.5.0.168                | binnie-mods-1.12.2-2.5.0.168.jar                | None                                     |
       | UCHIJ  | botany                  | 2.5.0.168                | binnie-mods-1.12.2-2.5.0.168.jar                | None                                     |
       | UCHIJ  | extrabees               | 2.5.0.168                | binnie-mods-1.12.2-2.5.0.168.jar                | None                                     |
       | UCHIJ  | extratrees              | 2.5.0.168                | binnie-mods-1.12.2-2.5.0.168.jar                | None                                     |
       | UCHIJ  | biomesoplenty           | 7.0.1.2399               | BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar   | None                                     |
       | UCHIJ  | bookshelf               | 2.3.559                  | Bookshelf-1.12.2-2.3.559.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCHIJ  | codechickenlib          | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCHIJ  | gregtech                | 0.5.9.88                 | gregtech-1.12.2-0.5.9.88.jar                    | None                                     |
       | UCHIJ  | ceu                     | 1.0.0.0                  | CEU-1.12.2-1.0.0.0.jar                          | None                                     |
       | UCHIJ  | redstoneflux            | 2.0.2                    | RedstoneFlux-1.12-2.0.2.3-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJ  | cofhcore                | 4.5.3                    | CoFHCore-1.12.2-4.5.3.20-universal.jar          | None                                     |
       | UCHIJ  | cofhworld               | 1.2.0                    | CoFHWorld-1.12.2-1.2.0.5-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJ  | controlling             | 3.0.6                    | Controlling-3.0.6.jar                           | None                                     |
       | UCHIJ  | cookingforblockheads    | 6.4.65                   | CookingForBlockheads_1.12.2-6.4.65.jar          | None                                     |
       | UCHIJ  | extendedrenderer        | v1.0                     | coroutil-1.12.1-1.2.13.jar                      | None                                     |
       | UCHIJ  | coroutil                | 1.12.1-1.2.13            | coroutil-1.12.1-1.2.13.jar                      | None                                     |
       | UCHIJ  | configmod               | v1.0                     | coroutil-1.12.1-1.2.13.jar                      | None                                     |
       | UCHIJ  | ctgui                   | 1.0.0                    | CraftTweaker2-1.12-4.1.9.jar                    | None                                     |
       | UCHIJ  | crafttweakerjei         | 2.0.2                    | CraftTweaker2-1.12-4.1.9.jar                    | None                                     |
       | UCHIJ  | ctm                     | MC1.12.2-0.3.2.18        | CTM-MC1.12.2-0.3.2.18.jar                       | None                                     |
       | UCHIJ  | cucumber                | 1.1.1                    | Cucumber-1.12.2-1.1.1.jar                       | None                                     |
       | UCHIJ  | dooglamooworlds         | 1.1.2                    | dooglamooworlds-1.12-1.1.2.jar                  | None                                     |
       | UCHIJ  | thermalfoundation       | 2.5.0                    | ThermalFoundation-1.12.2-2.5.0.19-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJ  | immersiveengineering    | 0.12-85                  | ImmersiveEngineering-0.12-85.jar                | 4cb49fcde3b43048c9889e0a3d083225da926334 |
       | UCHIJ  | engineersdoors          | 0.7.2                    | engineersdoors-0.7.2.jar                        | None                                     |
       | UCHIJ  | extendedcrafting        | 1.4.3                    | ExtendedCrafting-1.12.2-1.4.3.jar               | None                                     |
       | UCHIJ  | extrautils2             | 1.0                      | extrautils2-1.12-1.9.3.jar                      | None                                     |
       | UCHIJ  | foamfix                 | 0.10.1-1.12.2            | foamfix-0.10.1-1.12.2.jar                       | None                                     |
       | UCHIJ  | forgelin                | 1.7.4                    | Forgelin-1.7.4.jar                              | None                                     |
       | UCHIJ  | mekanism                | 1.12.2-9.4.13.349        | Mekanism-1.12.2-9.4.13.349.jar                  | None                                     |
       | UCHIJ  | placebo                 | 1.4.1                    | Placebo-1.12.2-1.4.1.jar                        | None                                     |
       | UCHIJ  | foundry                 | 3.3.4                    | Foundry-1.12.2-3.3.4.jar                        | None                                     |
       | UCHIJ  | ftblib                  | 5.3.0.53                 | FTBLib-5.3.0.53.jar                             | None                                     |
       | UCHIJ  | ftbutilities            | 5.3.0.51                 | FTBUtilities-5.3.0.51.jar                       | None                                     |
       | UCHIJ  | fw                      | 1.6.0                    | FullscreenWindowed-1.12-1.6.0.jar               | None                                     |
       | UCHIJ  | gamestages              | 2.0.98                   | GameStages-1.12.2-2.0.98.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCHIEE | gtadditions             | 1.12.2-1.1.0             | GregicAdditions-1.12.2-1.1.0.jar                | None                                     |
       | UCHI   | grimoireofgaia          | 1.6.3                    | GrimoireOfGaia3-1.12.2-1.6.3.jar                | None                                     |
       | UCHI   | gtcebees                | 1.12.2-1.0.1             | GTCEBees-1.12.2-1.0.1.jar                       | None                                     |
       | UCHI   | i18nmod                 | 1.12.2-1.0.6             | i18nupdatemod-1.12.2-1.0.6.jar                  | None                                     |
       | UCHI   | immersivepetroleum      | 1.1.9                    | immersivepetroleum-1.12.2-1.1.9.jar             | None                                     |
       | UCHI   | immersivetech           | 1.3.10                   | immersivetech-1.12-1.3.10.jar                   | None                                     |
       | UCHI   | teslacorelib            | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCHI   | industrialforegoing     | 1.12.2-1.12.2            | industrialforegoing-1.12.2-1.11.2-212.jar       | None                                     |
       | UCHI   | instantunify            | 1.1.2                    | instantunify-1.12.2-1.1.2.jar                   | None                                     |
       | UCHI   | harvestcraft            | 1.12.2z                  | Pam's HarvestCraft 1.12.2z.jar                  | None                                     |
       | UCHI   | integrationforegoing    | 1.12.2-1.7.4             | IntegrationForegoing-1.12.2-1.7.4.jar           | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
       | UCHI   | inventorytweaks         | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | UCHI   | jeibees                 | 0.9.0.5                  | jeibees-0.9.0.5-mc1.12.2.jar                    | None                                     |
       | UCHI   | jeiintegration          | 1.5.1.36                 | jeiintegration_1.12.2-1.5.1.36.jar              | None                                     |
       | UCHI   | jeivillagers            | 1.0                      | jeivillagers-1.12-1.0.2.jar                     | None                                     |
       | UCHI   | journeymap              | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                     | None                                     |
       | UCHI   | jeresources             | 0.8.5.27                 | JustEnoughResources-1.12.2-0.8.5.27.jar         | None                                     |
       | UCHI   | magicbees               | 1.0                      | MagicBees-1.12.2-3.1.10.jar                     | None                                     |
       | UCHI   | modelloader             | 1.1.3                    | modelloader-1.1.3.jar                           | None                                     |
       | UCHI   | magneticraft            | 2.5.1                    | Magneticraft_1.12-2.5.1-dev.jar                 | None                                     |
       | UCHI   | malisiscore             | 1.12.2-6.4.0             | malisiscore-1.12.2-6.4.0.jar                    | None                                     |
       | UCHI   | malisisdoors            | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                   | None                                     |
       | UCHI   | morebees                | 1.12.2-2.0.1             | morebees-1.12.2-2.0.1.jar                       | None                                     |
       | UCHI   | moreplates              | 5.2.1                    | moreplates-1.12.2-5.2.1.jar                     | None                                     |
       | UCHI   | mousetweaks             | 2.8                      | MouseTweaks-2.8-mc1.12.1.jar                    | None                                     |
       | UCHI   | multiblockstages        | 1.1.1                    | multiblockstages-1.1.1.jar                      | None                                     |
       | UCHI   | naturescompass          | 1.5.1                    | NaturesCompass-1.12.2-1.5.1.jar                 | None                                     |
       | UCHI   | norecipebook            | 1.2.1                    | noRecipeBook_v1.2.2formc1.12.2.jar              | None                                     |
       | UCHI   | primal                  | 0.6.90                   | PrimalCore-1.12.2-0.6.90.jar                    | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
       | UCHI   | questbook               | 3.1.1-1.12               | questbook-3.1.1-1.12.jar                        | None                                     |
       | UCHI   | questionablyimmersive   | @VERSION@                | questionablyimmersive-1.12.2-0.1.0.jar          | None                                     |
       | UCHI   | solcarrot               | 1.3.1                    | solcarrot-1.12.2-1.3.3.jar                      | None                                     |
       | UCHI   | spiceoflife             | 1.3.12                   | SpiceOfLife-mc1.12-1.3.12.jar                   | None                                     |
       | UCHI   | bq_standard             | 3.4.145                  | StandardExpansion-3.4.145.jar                   | None                                     |
       | UCHI   | valkyrielib             | 1.12.2-2.0.15.1          | valkyrielib-1.12.2-2.0.15.1.jar                 | None                                     |
       | UCHI   | universalmodifiers      | 1.12.2-1.0.9a            | valkyrielib-1.12.2-2.0.15.1.jar                 | None                                     |
       | UCHI   | vanillafix              | 1.0.9-97                 | VanillaFix-1.0.9-97.jar                         | None                                     |
       | UCHI   | worldstripper           | 1.5.1-1.12.2             | World-Stripper-1.5.1-1.12.2.jar                 | None                                     |
       | UCHI   | zombieawareness         | 1.12.1-1.11.14           | zombieawareness-1.12.1-1.11.14.jar              | None                                     |
       | UCHI   | hungeroverhaul          | 1.12.2-1.3.3.jenkins148  | HungerOverhaul-1.12.2-1.3.3.jenkins148.jar      | None                                     |
       | UCHI   | teslacorelib_registries | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                | None                                     |
  Loaded coremods (and transformers): MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
                                        
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      ForgelinPlugin (Forgelin-1.7.4.jar)
                                        
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      IELoadingPlugin (ImmersiveEngineering-core-0.12-85.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      AppleCore (AppleCore-mc1.12.2-3.1.4.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.9-97.jar)
                                        
                                      Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.10.1-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 398.82' Renderer: 'GeForce GTX 1080/PCIe/SSE2'
  Suspected Mods: Gregic Additions (gtadditions)
  Launched Version: forge-14.23.4.2760
  LWJGL: 2.9.4
  OpenGL: GeForce GTX 1080/PCIe/SSE2 GL version 4.6.0 NVIDIA 398.82, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: Minecraft-Mod-Language-Modpack.zip
  Current Language: 简体中文 (中国)
  Profiler Position: N/A (disabled)
  CPU: 12x Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz

**Comment by Rongmario** [comment]
How'd you know its with Mekanism?

**Comment by xly2000** [comment]
> How'd you know its with Mekanism?

Exclusion method
