### ISSUE TITLE
Make Clean Stainless Casings Non-Spawning

### ISSUE THREAD

**Issue by Folanlron** [EmosewaPixel/GregicAdditions#42]
When setting up Distillation tower for refining, First tower will always have enemies spawning inside(kind of annoying in Gregblock pack, with not having spawn disabling torches..) This is due too size anything that has > 2 empty space height inside the multi-block will spawn mobs.

And tower needs too "lock" output, really annoying having them change all the time.

**Comment by EmosewaPixel** [comment]
The problem is that the energy hatches (really all hatches in general) allow mob spawning on them.
