### ISSUE TITLE
Config to put back fine wire into wiremill if cluster mill is disabled?

### ISSUE THREAD

**Issue by Vyraal1** [EmosewaPixel/GregicAdditions#43]
Seems like here https://github.com/EmosewaPixel/GregicAdditions/blob/d0967c31bee2d0e8debcad9b84201a77998e4e6a/src/main/java/gregicadditions/recipes/GAMachineRecipeRemoval.java#L58 fine wire is removed from the wiremill and added to the cluster mill. However there is no configs to add it back to the wiremill if clustermill is also disabled. Could you add configs to disable the recipe and add it back similar to how you allow configs to add back foils to metal bender?

**Comment by EmosewaPixel** [comment]
I'm just going to assume you derped here, since this issue simply doesn't make sense.
