### ISSUE TITLE
GTCE build 1.6 now has alot of redundancies with GA

### ISSUE THREAD

**Issue by Saereth** [EmosewaPixel/GregicAdditions#52]
Trying to help out by comparing GTCE182+GA vs the new GTCE1.6 standalone from what I can tell
these items are now completely obsolete, deprecated or just plain have overlapping functionality now
in the case of GA's cricuits and circuit assembler. Do with this report as you will, I hope its useful to you.

Circuit assembler (All tiers)
All circuits including all variants of circuits or any $circuitX oredict items 
supercomputers
mainframes
crystalcomputers
advanced alloy
mixed metal ingots
bick forms (all variants)
compressed fireclay
unfired clay brick

pretty much ALL the wafers
silicone boules (all variants)
raw carbon fiber
raw crystal chips
crystal processing unit
crystal SOC
lapotron crystals
iridium alloy plate
uncompressed iridium alloy plate
vacuum tube
all SMD components: transistor, resistor, capacitor, diode, small coil
electrical components: small coil, resistor, glass tube, capacitor, diode, vacuum tube
all circuit boards
stem cells

All of GA's materials except:
fish oil
CarbonMonoxde
RawGrowthMedium
SterilizedGrowthMedium
Meat
NeutralMatter
PositiveMatter
Neutronium
lignite coke
Extreme
Infinite

**Comment by EmosewaPixel** [comment]
I'm aware. When the update dropped it was too late for me to work on it. I'm going to go through every single thing.
