### ISSUE TITLE
Crashed with GA Compat on sponge server

### ISSUE THREAD

**Issue by Akiraca** [EmosewaPixel/GregicAdditions#56]
GTCE version: 1.6.6.374
GA version: 1.4.2
GA Compatibility version: 1.1
forge version: 14.23.5.2779 (required by railcraft)
sponge version: 2768-7.1.5 (highest version avaliable)

Note that without GA Compatibility (but with GA and GTCE) everything goes well

![image](https://user-images.githubusercontent.com/23720781/55225038-d7f76500-5265-11e9-8e84-f00271101a71.png)

**Comment by EmosewaPixel** [comment]
You don't need GA compat.
